<%
Option Explicit
%>
<script language="JavaScript" runat="server">
var d = new Date().toUTCString();
</script>
<!-- #INCLUDE file="mylib-buildquery.asp" -->
<%
Dim sQuery, sMode, sHelpURI, X
Dim bPersistent

If Request.QueryString("action") <> "Build" And Request.QueryString("action") <> "" Then
	If Request.QueryString("action") = "Help" Then
		sHelpURI = "mylib-doc.asp"
		if Request.QueryString("helptopic") <> "" Then
			sHelpURI = sHelpURI & "#" & Request.QueryString("helptopic")
		End If
		Response.Redirect(sHelpURI)
	End If
        sQuery = "?"
	For Each X in Request.QueryString 
		If LCase(X) <> "action" And LCase(X) <> "helptopic" Then
		        sQuery = sQuery & X & "=" & Request.QueryString(X) & "&"
                End If
	Next

	sMode = Mid(Request.QueryString("action"), 6)
	If Request.QueryString("ashtml") <> "" And sMode = "XHTML" Then sMode = sMode & "asHTML"
	sQuery = sQuery & "mode=" & sMode
	Response.Redirect("mylib-test.asp" & sQuery)
End If

Response.ContentType = "text/javascript"
If Request.QueryString("action") = "Build" Then
	Response.AddHeader "Content-Disposition","attachment; filename=mylib.js"
End If
%>
/*

 Generated by My Library Builder v<%=strVersion%> (http://www.cinsoft.net/mylib-builder.asp)

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 Modified copies of the Software must be renamed.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.

*/
// <% Response.Write(d & vbCrLf) %>
<!-- #INCLUDE file="mylib.asp" -->